version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: stage2-devops
    ports:
      - "8080:80"
    environment:
      - PORT=${PORT}
      - ACTIVE_POOL=${ACTIVE_POOL}
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx-real:/var/log/nginx-real
    networks:
      - app_network

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app_network

  watcher:
    build:
      context: ./watcher
      dockerfile: Dockerfile
    container_name: watcher
    env_file: .env
    depends_on:
      - nginx
    volumes:
      - ./nginx-real:/var/log/nginx-real
      - ./watcher:/app:rw
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs:

